### ISSUE TITLE
Gra potrzebuje stylu

### ISSUE THREAD

**Issue by AppleC4T** [AppleC4T/WeeklyGameJam77#1]
Musimy wybrać styl grafiki (np. fantasy).
Ja proponuję średniowieczny, można wtedy wpleść w to mechanikę gry (1. wymiar - średniowieczny loch/opuszczona posiadłość, rycerz jako postać walczy z bandytami i złodziejami próbującymi okraść pozostałości; 2. wymiar - świat duchów nawiedzających miejsce, łuczniczka duch jako postać walczy z innymi duchami, które tylko ona może pokonać jako duch). Napisz co uważasz w komentarzach.

**Comment by Flop3r** [comment]
Ok, wydaję mi się, że średniowiecze jest ok
