### ISSUE TITLE
Klasy

### ISSUE THREAD

**Issue by Flop3r** [AppleC4T/WeeklyGameJam77#3]
Musimy ustalić klasy (czy w ogóle będą a jeżeli tak to ilość).
Każda klasa potrzebuje również własną mechanikę/ ułatwienie/ umiejętność.

**Comment by AppleC4T** [comment]
Ze względu na czas ja bym zrobil bez klas, to znaczy bez wyboru postaci przed grą. Natomiast zrobiłbym podział postaci w wymiarach. W pierwszym zwyklym jest rycerz, który ma dużo hp, bije z bliska i może sie bronić tarczą i tylko chodzi po ziemi, a w drugim jest łuczniczka duch, którą może się sterować na odwrót (do ustalenia), ale na pewno ma mniej hp, bije na zasieg i przez to ze jest duchem moze latać. Wtedy można zrobić pokoje, które wymagają przelecenia gdzies jako łuczniczka i utorowanie miejsca rycerzowi zeby przejść dalej.

**Comment by Flop3r** [comment]
Ok, więc w naszej grze nie będzie możliwości innej klasy z unikalnymi umiejętnościami oraz mechanikami. 
W trakcie gry podczas "podróży" między wymiarami będą zmieniać się cechy głównego bohatera. Zamykam.
